# Generated by Django 2.1.5 on 2019-01-18 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20190118_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unlike',
            new_name='Dislike',
        ),
    ]
